# Generate your age key:
# age-keygen -o ~/.config/sops/age/keys.txt
# Get public key: age-keygen -y ~/.config/sops/age/keys.txt

# Uncomment and configure when you set up SOPS:
# keys:
#   - &hosts:
#     - &your-host: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# creation_rules:
#   - path_regex: secrets/secrets.yaml$
#     key_groups:
#       - age:
#         - *your-host